In [52]:
import pandas as pd 
import re
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')
from collections import Counter

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\garge\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [23]:
df = pd.read_excel("Instacomments.xlsx")

In [24]:
print("HEAD:/n",df.head())

HEAD:/n                                                 text  Unnamed: 1  Unnamed: 2  \
0  Why it's taking so long to get your product de...         NaN         NaN
1  Hey I please send my order details or the day ...         NaN         NaN
2                    Hey place send my order details         NaN         NaN
3                          Please send order details         NaN         NaN
4  Hello .. I’m using  your alpha arbutin during ...         NaN         NaN

   Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN

   Unnamed: 9  ...  Unnamed: 12  Unnamed: 13 Unnamed: 14 Unnamed: 15  \
0         NaN  ...          NaN          NaN         NaN         NaN
1         NaN  ...          NaN          NaN         NaN         NaN
2         NaN  ...          NaN          NaN         NaN         NaN
3         NaN  ...          NaN          NaN         NaN         NaN
4         NaN  ...          NaN          NaN         NaN         NaN

   Unnamed: 16  Unnamed: 17 Unnamed: 18 Unnamed: 19 Unnamed: 20  Unnamed: 21
0          NaN          NaN         NaN         NaN         NaN          NaN
1          NaN          NaN         NaN         NaN         NaN          NaN
2          NaN          NaN         NaN         NaN         NaN          NaN
3          NaN          NaN         NaN         NaN         NaN          NaN
4          NaN          NaN         NaN         NaN         NaN          NaN

[5 rows x 22 columns]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   text         780 non-null    object
 1   Unnamed: 1   0 non-null      float64
 2   Unnamed: 2   0 non-null      float64
 3   Unnamed: 3   0 non-null      float64
 4   Unnamed: 4   0 non-null      float64
 5   Unnamed: 5   0 non-null      float64
 6   Unnamed: 6   0 non-null      float64
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  0 non-null      float64
 12  Unnamed: 12  57 non-null     object
 13  Unnamed: 13  57 non-null     object
 14  Unnamed: 14  42 non-null     float64
 15  Unnamed: 15  42 non-null     float64
 16  Unnamed: 16  42 non-null     object
 17  Unnamed: 17  42 non-null     object
 18  Unnamed: 18  42 non-null     object
 19  Unnamed: 19  539 non-null    float64
 20  Unnamed: 20  539 non-null    object
 21  Unnamed: 21  539 non-null    object
dtypes: float64(14), object(8)
memory usage: 134.2+ KB

In [26]:
df.isnull().sum()

text             0
Unnamed: 1     780
Unnamed: 2     780
Unnamed: 3     780
Unnamed: 4     780
Unnamed: 5     780
Unnamed: 6     780
Unnamed: 7     780
Unnamed: 8     780
Unnamed: 9     780
Unnamed: 10    780
Unnamed: 11    780
Unnamed: 12    723
Unnamed: 13    723
Unnamed: 14    738
Unnamed: 15    738
Unnamed: 16    738
Unnamed: 17    738
Unnamed: 18    738
Unnamed: 19    241
Unnamed: 20    241
Unnamed: 21    241
dtype: int64

In [27]:
df = df[['text']]

In [28]:
df.rename(columns={'text': 'comment'}, inplace=True)

In [29]:
df.dropna(subset=['comment'],inplace=True)

In [30]:
df.reset_index(drop=True,inplace=True)

In [31]:
df.head()

                                             comment
0  Why it's taking so long to get your product de...
1  Hey I please send my order details or the day ...
2                    Hey place send my order details
3                          Please send order details
4  Hello .. I’m using  your alpha arbutin during ...

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   comment  780 non-null    object
dtypes: object(1)
memory usage: 6.2+ KB

In [33]:
df.isnull()

     comment
0      False
1      False
2      False
3      False
4      False
..       ...
775    False
776    False
777    False
778    False
779    False

[780 rows x 1 columns]

Data cleanig using NLP

In [34]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z ]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

Applying changes

In [35]:
df['clean_comment'] = df['comment'].apply(clean_text)

In [36]:
print(df.columns)

Index(['comment', 'clean_comment'], dtype='object')

In [37]:
df[['comment', 'clean_comment']].head()

,comment,clean_comment
0,Why it's taking so long to get your product de...,why its taking so long to get your product del...
1,Hey I please send my order details or the day ...,hey i please send my order details or the day ...
2,Hey place send my order details,hey place send my order details
3,Please send order details,please send order details
4,Hello .. I’m using your alpha arbutin during ...,hello im using your alpha arbutin during the d...

Let us start with sentiment analysis

Here i will take each comment into any 3 of below 
Positive 
Negative 
Netural

In [38]:
sia = SentimentIntensityAnalyzer() #Initialization of model

In [39]:
def get_sentiment(text):
    score = sia.polarity_scores(text)['compound']  
    
    if score > 0:
        return "Positive"
    elif score < 0:
        return "Negative"
    else:
        return "Neutral"

In [40]:
df['sentiment']=df['clean_comment'].apply(get_sentiment)

In [21]:
df[['clean_comment', 'sentiment']].head(10)

                                       clean_comment sentiment
0  why its taking so long to get your product del...   Neutral
1  hey i please send my order details or the day ...  Positive
2                    hey place send my order details   Neutral
3                          please send order details  Positive
4  hello im using your alpha arbutin during the d...  Positive
5  which concentration of retinol is better for t...  Positive
6        what is best for white heads and open pores  Positive
7  which serum is best for dark marks and hyperpi...  Positive
8  very happy with ur serumsalpha arbutin n also ...  Positive
9  also my skin is dry n i m this yr which retino...  Positive

Lets Start Analysis

In [51]:
df['sentiment'].value_counts()

sentiment
Positive    376
Neutral     344
Negative     60
Name: count, dtype: int64

we can see that most comments are positive 

Inquery type of coments are nautral

and there are very less negative comments

Now we will se comment length according to reviews

In [46]:
df['comment_length'] = df['clean_comment'].apply(len)

In [47]:
df['word_count'] = df['clean_comment'].apply(lambda x: len(x.split()))

In [48]:
df.groupby('sentiment')['comment_length'].mean()

sentiment
Negative    134.816667
Neutral      46.116279
Positive    108.646277
Name: comment_length, dtype: float64

Here we can see that negative comments are more long

Now lets find some real insights

In [53]:
all_words = " ".join(df['clean_comment']).split()
Counter(all_words).most_common(10)

[('i', 572),
 ('and', 364),
 ('to', 245),
 ('can', 244),
 ('the', 243),
 ('this', 235),
 ('use', 234),
 ('skin', 222),
 ('it', 216),
 ('is', 196)]

In [54]:
df.to_csv("clean_instagram_data.csv", index=False)